#+TITLE: HOW TO CHECK OUT YOUR REPO

So we'll be submitting most of our assignments via SVN, as you used in
your CSSE120/220/230 classes.  As many of our assignments will be
java, you may use eclipse to manage them.  Or you can use any editor
you prefer, but I won't be making projects or testing that builds work
in the case.

* Figuring out your Repo URL

To do that you need to figure out your year code.  Your year code is
the year of the later part of the academic term (so if it is the
2014-2015 term, the year is 2015) followed by either 10 (fall) 20
(winter) or 30 (spring).

Once you know that, your repo url should be:
http://svn.csse.rose-hulman.edu/repos/csseCOURSENUM-YEARCODE-YOURNETID

So for example, if I was taking CSSE375 in Spring 2014-2015, my
url would be:

http://svn.csse.rose-hulman.edu/repos/csse375-201530-hewner

* Checking out on the command line

Once you have the URL, you can checkout like this:

: svn co http://svn.csse.rose-hulman.edu/repos/csse375-201530-hewner

Use svn commit to make changes to your repo.
Use svn update to get new homework assignments when they're released.

If you're not sure how to use svn, try asking a friend or online
tutorial.  But I'm always available as a backup if that doesn't work
:D.

* Checking out in Eclipse

First, you need to install the subclipse plugin to eclipse.  Download and install it from here: 

http://subclipse.tigris.org

Then go to

Window menu > Show View > Other > SVN > Svn Repositories

That should open the svn repositories view.  Then right click in the window and select New Repository Location.  From there, a dialog should appear that you add your URL to.

* If you don't have your SVN Password
You'll need to use your svn password to check it out.  If you need
it reset, email me.
